export const ROUTER = {
  // Auth
  AUTH: '/auth',
  LOGIN: '/login',
  ID_FIND: '/id-find',
  PASSWORD_RESET: '/password-reset',
  SIGNUP: 'signup',
  SIGNUP_FORM: 'signup-form',
  SOCIAL_CHECK: '/social-check',
  // 마이페이지
  MYPAGE: '/mypage',
  KEEP_LIST: 'keep-list',
  CHAT_LIST: 'chat-list',

  SUPPORT: '/support',
  ABOUT: '/about',
  BARO_TALK: '/baro-talk',
  LEGAL_DICTIONARY: '/legal-dictionary',
  LAWYER_SEARCH: '/lawyer-search',
  LAW_FIRM: '/law-firm',
  MAIN: '/',
  SUB_MAIN: '/:subcategoryId',
  BLOG: '/blog',
  BLOG_DETAIL: '/blog/:blogId',
  VIDEO: '/video',
  LEGAL_KNOWLEDGE: '/legal-knowledge',
  LAWYER: '/lawyer',
  REQUEST_BARO_TALK: '/request-baro-talk',
  CONSULTATION_CONTENT_FORM: '/consultation-content-form',
  BARO_TALK_LAWYER_SELECTION: '/baro-talk-lawyer-selection',
  SEARCH_MAIN: '/search',
  MOBILE_MENU_LIST: '/mobile-menu-list',
  FAQ: '/faq',
  SUPPORT_NOTICE: '/support-notice',
  LAWYER_DETAIL: '/lawyer',
  NOT_FOUND: '*',
} as const
