export const ROUTER = {
  LOGIN: '/login',
  MYPAGE: '/mypage',
  SUPPORT: '/support',
  ABOUT: '/about',
  BARO_TALK: '/baro-talk',
  LEGAL_DICTIONARY: '/legal-dictionary',
  LAWYER_SEARCH: '/lawyer-search',
  LAW_FIRM: '/law-firm',
  MAIN: '/',
  SUB_MAIN: '/:subcategoryId',
  BLOG: '/blog',
  BLOG_DETAIL: '/blog/:blogId',
  VIDEO: '/video',
  LEGAL_KNOWLEDGE: '/legal-knowledge',
  LAWYER: '/lawyer',
  REQUEST_BARO_TALK: '/request-baro-talk',
  CONSULTATION_CONTENT_FORM: '/consultation-content-form',
  BARO_TALK_LAWYER_SELECTION: '/baro-talk-lawyer-selection',
  SEARCH_MAIN: '/search',
  NOT_FOUND: '*',
} as const
