export const SORT_CASE = [
  {
    key: 'all',
    name: '전체',
  },
  {
    key: 'recommend',
    name: '추천수',
  },
  {
    key: 'like',
    name: '공감순',
  },
  {
    key: 'new',
    name: '최신순',
  },
] as const

export const mockupCategoryList = [
  {
    id: 2,
    categoryName: '금융/재산',
    imageUrl: 'https://djsf6237taw1.cloudfront.net/allbarlaw/icons/1727681287576_ê¸ìµìì° 17.png',
    clickedImageUrl: 'https://djsf6237taw1.cloudfront.net/allbarlaw/icons/1727681295582_ê¸ìµìì° 18.png',
    isUncategorized: false,
    subcategories: [
      {
        id: 2,
        subcategoryName: '사기/공갈',
        isUncategorized: false,
        categoryId: 2,
      },
      {
        id: 12,
        subcategoryName: '절도/재물손괴/주거침입',
        isUncategorized: false,
        categoryId: 2,
      },
      {
        id: 15,
        subcategoryName: '횡령/배임',
        isUncategorized: false,
        categoryId: 2,
      },
    ],
  },
  {
    id: 3,
    categoryName: '음주/교통',
    imageUrl: 'https://djsf6237taw1.cloudfront.net/allbarlaw/icons/1727681390124_ìì£¼êµíµ 1.png',
    clickedImageUrl: 'https://djsf6237taw1.cloudfront.net/allbarlaw/icons/1727681396852_ìì£¼êµíµ 2.png',
    isUncategorized: false,
    subcategories: [
      {
        id: 3,
        subcategoryName: '음주운전',
        isUncategorized: false,
        categoryId: 3,
      },
      {
        id: 8,
        subcategoryName: '무면허운전',
        isUncategorized: false,
        categoryId: 3,
      },
      {
        id: 10,
        subcategoryName: '교통사고/보복운전',
        isUncategorized: false,
        categoryId: 3,
      },
      {
        id: 16,
        subcategoryName: '뺑소니',
        isUncategorized: false,
        categoryId: 3,
      },
    ],
  },
  {
    id: 4,
    categoryName: '보이스피싱',
    imageUrl: 'https://djsf6237taw1.cloudfront.net/allbarlaw/icons/1727681405713_ë³´ì´ì¤í¼ì±ìì° 16.png',
    clickedImageUrl: 'https://djsf6237taw1.cloudfront.net/allbarlaw/icons/1727681410092_ë³´ì´ì¤í¼ì±ìì° 17.png',
    isUncategorized: false,
    subcategories: [
      {
        id: 5,
        subcategoryName: '명의대여/도용',
        isUncategorized: false,
        categoryId: 4,
      },
      {
        id: 13,
        subcategoryName: '보이스피싱/유사수신',
        isUncategorized: false,
        categoryId: 4,
      },
    ],
  },
  {
    id: 5,
    categoryName: '도박',
    imageUrl: 'https://djsf6237taw1.cloudfront.net/allbarlaw/icons/1727681420868_ëë°ìì° 21 1.png',
    clickedImageUrl: 'https://djsf6237taw1.cloudfront.net/allbarlaw/icons/1727681423430_ëë°ìì° 21 2.png',
    isUncategorized: false,
    subcategories: [
      {
        id: 11,
        subcategoryName: '도박',
        isUncategorized: false,
        categoryId: 5,
      },
    ],
  },
  {
    id: 6,
    categoryName: '마약',
    imageUrl: 'https://djsf6237taw1.cloudfront.net/allbarlaw/icons/1727681428301_ã´ (1).png',
    clickedImageUrl: 'https://djsf6237taw1.cloudfront.net/allbarlaw/icons/1727681431025_ë§ì½.png',
    isUncategorized: false,
    subcategories: [
      {
        id: 14,
        subcategoryName: '마약/대마',
        isUncategorized: false,
        categoryId: 6,
      },
    ],
  },
  {
    id: 7,
    categoryName: '부동산',
    imageUrl: 'https://djsf6237taw1.cloudfront.net/allbarlaw/icons/1727681438742_ìì° 1.png',
    clickedImageUrl: 'https://djsf6237taw1.cloudfront.net/allbarlaw/icons/1727681444301_ìì° 5.png',
    isUncategorized: false,
    subcategories: [
      {
        id: 24,
        subcategoryName: '명도소송',
        isUncategorized: false,
        categoryId: 7,
      },
      {
        id: 25,
        subcategoryName: '재개발/재건축/지주택',
        isUncategorized: false,
        categoryId: 7,
      },
      {
        id: 26,
        subcategoryName: '하자/누수/층간소음',
        isUncategorized: false,
        categoryId: 7,
      },
      {
        id: 27,
        subcategoryName: '공사대금',
        isUncategorized: false,
        categoryId: 7,
      },
      {
        id: 28,
        subcategoryName: '수용/보상',
        isUncategorized: false,
        categoryId: 7,
      },
      {
        id: 29,
        subcategoryName: '매매/경매',
        isUncategorized: false,
        categoryId: 7,
      },
      {
        id: 30,
        subcategoryName: '권리금/보증금',
        isUncategorized: false,
        categoryId: 7,
      },
      {
        id: 31,
        subcategoryName: '주택/상가임대차',
        isUncategorized: false,
        categoryId: 7,
      },
      {
        id: 32,
        subcategoryName: '기타부동산',
        isUncategorized: false,
        categoryId: 7,
      },
    ],
  },
  {
    id: 8,
    categoryName: '소년/학폭',
    imageUrl: 'https://djsf6237taw1.cloudfront.net/allbarlaw/icons/1727681453169_íí­ìì° 1.png',
    clickedImageUrl: 'https://djsf6237taw1.cloudfront.net/allbarlaw/icons/1727681455875_íí­ìì° 2.png',
    isUncategorized: false,
    subcategories: [
      {
        id: 6,
        subcategoryName: '아동학대',
        isUncategorized: false,
        categoryId: 8,
      },
      {
        id: 7,
        subcategoryName: '소년사건',
        isUncategorized: false,
        categoryId: 8,
      },
      {
        id: 9,
        subcategoryName: '학교폭력/왕따',
        isUncategorized: false,
        categoryId: 8,
      },
    ],
  },
  {
    id: 9,
    categoryName: '환경/행정',
    imageUrl: 'https://djsf6237taw1.cloudfront.net/allbarlaw/icons/1727681464857_ã´ (6).png',
    clickedImageUrl: 'https://djsf6237taw1.cloudfront.net/allbarlaw/icons/1727681468249_íê²½, íì .png',
    isUncategorized: false,
    subcategories: [
      {
        id: 51,
        subcategoryName: '환경/행정',
        isUncategorized: false,
        categoryId: 9,
      },
    ],
  },
  {
    id: 10,
    categoryName: '회생/파산',
    imageUrl: 'https://djsf6237taw1.cloudfront.net/allbarlaw/icons/1727681472035_íìíì°ìì° 24 1.png',
    clickedImageUrl: 'https://djsf6237taw1.cloudfront.net/allbarlaw/icons/1727681475089_íìíì°ìì° 24 2.png',
    isUncategorized: false,
    subcategories: [
      {
        id: 38,
        subcategoryName: '개인회생/파산',
        isUncategorized: false,
        categoryId: 10,
      },
      {
        id: 40,
        subcategoryName: '법인회생/파산',
        isUncategorized: false,
        categoryId: 10,
      },
    ],
  },
  {
    id: 11,
    categoryName: '민사',
    imageUrl: 'https://djsf6237taw1.cloudfront.net/allbarlaw/icons/1727681498927_ë¯¼ì¬ìì° 2 3.png',
    clickedImageUrl: 'https://djsf6237taw1.cloudfront.net/allbarlaw/icons/1727681502296_ë¯¼ì¬ìì° 2 4.png',
    isUncategorized: false,
    subcategories: [
      {
        id: 33,
        subcategoryName: '채권압류/추심',
        isUncategorized: false,
        categoryId: 11,
      },
      {
        id: 34,
        subcategoryName: '대여금/중도금',
        isUncategorized: false,
        categoryId: 11,
      },
      {
        id: 35,
        subcategoryName: '손해배상/위자료',
        isUncategorized: false,
        categoryId: 11,
      },
      {
        id: 36,
        subcategoryName: '계약검토/해지',
        isUncategorized: false,
        categoryId: 11,
      },
      {
        id: 37,
        subcategoryName: '기타민사',
        isUncategorized: false,
        categoryId: 11,
      },
      {
        id: 47,
        subcategoryName: '민사절차',
        isUncategorized: false,
        categoryId: 11,
      },
    ],
  },
  {
    id: 12,
    categoryName: '일반형사',
    imageUrl: 'https://djsf6237taw1.cloudfront.net/allbarlaw/icons/1727681525852_ã´ (5).png',
    clickedImageUrl: 'https://djsf6237taw1.cloudfront.net/allbarlaw/icons/1727681529588_íì¬.png',
    isUncategorized: false,
    subcategories: [
      {
        id: 4,
        subcategoryName: '폭행/상해',
        isUncategorized: false,
        categoryId: 12,
      },
      {
        id: 17,
        subcategoryName: '협박/모욕',
        isUncategorized: false,
        categoryId: 12,
      },
      {
        id: 18,
        subcategoryName: '형사절차',
        isUncategorized: false,
        categoryId: 12,
      },
      {
        id: 19,
        subcategoryName: '위증/무고',
        isUncategorized: false,
        categoryId: 12,
      },
      {
        id: 20,
        subcategoryName: '명예훼손',
        isUncategorized: false,
        categoryId: 12,
      },
      {
        id: 21,
        subcategoryName: '뇌물/문서위조',
        isUncategorized: false,
        categoryId: 12,
      },
      {
        id: 22,
        subcategoryName: '기타형사',
        isUncategorized: false,
        categoryId: 12,
      },
      {
        id: 23,
        subcategoryName: 'IT/개인정보',
        isUncategorized: false,
        categoryId: 12,
      },
    ],
  },
  {
    id: 13,
    categoryName: '의료',
    imageUrl: 'https://djsf6237taw1.cloudfront.net/allbarlaw/icons/1727681533588_ìë£ 1.png',
    clickedImageUrl: 'https://djsf6237taw1.cloudfront.net/allbarlaw/icons/1727681536417_ìë£ 2.png',
    isUncategorized: false,
    subcategories: [
      {
        id: 48,
        subcategoryName: '의료',
        isUncategorized: false,
        categoryId: 13,
      },
    ],
  },
  {
    id: 14,
    categoryName: '기업',
    imageUrl: 'https://djsf6237taw1.cloudfront.net/allbarlaw/icons/1727681542231_ê¸°ì 1.png',
    clickedImageUrl: 'https://djsf6237taw1.cloudfront.net/allbarlaw/icons/1727681544854_ê¸°ì 2.png',
    isUncategorized: false,
    subcategories: [
      {
        id: 45,
        subcategoryName: '기업',
        isUncategorized: false,
        categoryId: 14,
      },
    ],
  },
  {
    id: 15,
    categoryName: '노동/인사',
    imageUrl: 'https://djsf6237taw1.cloudfront.net/allbarlaw/icons/1727681563017_ã´ (3).png',
    clickedImageUrl: 'https://djsf6237taw1.cloudfront.net/allbarlaw/icons/1727681566503_ì¸ì¬.png',
    isUncategorized: false,
    subcategories: [
      {
        id: 49,
        subcategoryName: '노동/인사',
        isUncategorized: false,
        categoryId: 15,
      },
    ],
  },
  {
    id: 16,
    categoryName: '이혼/가사',
    imageUrl: 'https://djsf6237taw1.cloudfront.net/allbarlaw/icons/1727681593551_ã´ (2).png',
    clickedImageUrl: 'https://djsf6237taw1.cloudfront.net/allbarlaw/icons/1727681600252_ì´í¼.png',
    isUncategorized: false,
    subcategories: [
      {
        id: 39,
        subcategoryName: '조정/협의이혼',
        isUncategorized: false,
        categoryId: 16,
      },
      {
        id: 41,
        subcategoryName: '상속/유류분',
        isUncategorized: false,
        categoryId: 16,
      },
      {
        id: 42,
        subcategoryName: '양육권/양육비',
        isUncategorized: false,
        categoryId: 16,
      },
      {
        id: 43,
        subcategoryName: '양육권/양육비',
        isUncategorized: false,
        categoryId: 16,
      },
      {
        id: 44,
        subcategoryName: '기타가사',
        isUncategorized: false,
        categoryId: 16,
      },
      {
        id: 46,
        subcategoryName: '상간/불륜',
        isUncategorized: false,
        categoryId: 16,
      },
      {
        id: 59,
        subcategoryName: '재판이혼',
        isUncategorized: false,
        categoryId: 16,
      },
    ],
  },
  {
    id: 17,
    categoryName: '세금',
    imageUrl: 'https://djsf6237taw1.cloudfront.net/allbarlaw/icons/1727681609504_ã´ (4).png',
    clickedImageUrl: 'https://djsf6237taw1.cloudfront.net/allbarlaw/icons/1727681612867_ì¡°ì¸.png',
    isUncategorized: false,
    subcategories: [
      {
        id: 52,
        subcategoryName: '세금',
        isUncategorized: false,
        categoryId: 17,
      },
    ],
  },
  {
    id: 18,
    categoryName: '지식재산권',
    imageUrl: 'https://djsf6237taw1.cloudfront.net/allbarlaw/icons/1727681625154_ìì° 4.png',
    clickedImageUrl: 'https://djsf6237taw1.cloudfront.net/allbarlaw/icons/1727681628561_ìì° 6.png',
    isUncategorized: false,
    subcategories: [
      {
        id: 50,
        subcategoryName: '지식재산권',
        isUncategorized: false,
        categoryId: 18,
      },
    ],
  },
  {
    id: 19,
    categoryName: '성범죄',
    imageUrl: 'https://djsf6237taw1.cloudfront.net/allbarlaw/icons/1727681644283_ì±ë²ì£ìì° 5.png',
    clickedImageUrl: 'https://djsf6237taw1.cloudfront.net/allbarlaw/icons/1727681647444_ì±ë²ì£ìì° 6.png',
    isUncategorized: false,
    subcategories: [
      {
        id: 53,
        subcategoryName: '강간/유사강간',
        isUncategorized: false,
        categoryId: 19,
      },
      {
        id: 54,
        subcategoryName: '성추행/성희롱',
        isUncategorized: false,
        categoryId: 19,
      },
      {
        id: 55,
        subcategoryName: '데이트폭력',
        isUncategorized: false,
        categoryId: 19,
      },
      {
        id: 56,
        subcategoryName: '성매매',
        isUncategorized: false,
        categoryId: 19,
      },
      {
        id: 57,
        subcategoryName: '미성년자성범죄',
        isUncategorized: false,
        categoryId: 19,
      },
      {
        id: 58,
        subcategoryName: '디지털/통매음',
        isUncategorized: false,
        categoryId: 19,
      },
    ],
  },
]
