export const QUERY_KEY = {
  CATEGORY: 'category',
  BLOG_COUNT: 'blogCount',
  BLOG_LIST: 'blogList',
  RANDOM_BLOG_LIST: 'randomBlogList',
  BLOG_DETAIL: 'blogDetail',
  VIDEO_COUNT: 'videoCount',
  VIDEO_LIST: 'videoList',
  RANDOM_VIDEO_LIST: 'randomVideoList',
  KNOWLEDGE_LIST: 'knowledgeList',
  KNOWLEDGE_DETAIL: 'knowledgeDetail',
  BANNER: 'banner',
  LAWFIRM_LIST: 'lawfirmList',
  TRACK_VIEW: 'trackView',
  NOTICE_TYPES: 'noticeTypes',
  NOTICE_LIST: 'noticeList',
  NOTICE_DETAIL: 'noticeDetail',
} as const
